**De lista a numpy array**


In [2]:
import numpy as np
#lista a
a=[[11,12,13],[21,22,23],[31,32,33]]
#Convierte la lista a en array
A=np.array(a)
A
A.ndim
A.shape
A.size
A[0][0]
A[0,1]
A[0,0:2]
A[0:2,2]


array([13, 23])

**Suma y Resta de "matrices"**


In [ ]:
X=np.array([[1,0],[0,1]])
Y=np.array([[2,1],[1,2]])
Z=X+Y
Z


array([[3, 1],
       [1, 3]])

**Multiplicación por escalar**

In [ ]:
 Y=np.array([[2,1],[1,2]])
 Z=2*Y
 Z
 

array([[4, 2],
       [2, 4]])

**Producto Hadamard**

In [3]:
X=np.array([[1,0],[0,1]])
Y=np.array([[2,1],[1,2]])
Z=X*Y
Z

array([[2, 0],
       [0, 2]])

**Multiplicación de Matrices**


In [4]:
A=np.array([[0,1,1],[1,0,1]])
B=np.array([[1,1],[1,1],[-1,1]])
C=np.dot(A,B)
C

array([[0, 2],
       [0, 2]])